In [83]:
import numpy as np

In [ ]:
np.linspace(10,30,6)

array([10., 14., 18., 22., 26., 30.])

In [3]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
arr3d = np.array([[ [1,2,3] ,[4,5,6] , [10,25,35] ,[40,50,60]] , [[10,20,30] , [5,10,20] ,[11,22,33] ,[44,55,66] ]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 25, 35],
        [40, 50, 60]],

       [[10, 20, 30],
        [ 5, 10, 20],
        [11, 22, 33],
        [44, 55, 66]]])

In [87]:
arr3d.size

30

In [6]:
arr3d.ndim

3

In [7]:
arr3d.shape

(2, 4, 3)

# Bir array'i reshape(Yenideb şekillendirme)Etme 

In [8]:
#.reshape() methodu arrayin şeklini değiştirmeye yarar.
#.reshape() yaparken toplam eleman sayısını sabit tutmaya dikkat edilmeli.

In [9]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 25, 35],
        [40, 50, 60]],

       [[10, 20, 30],
        [ 5, 10, 20],
        [11, 22, 33],
        [44, 55, 66]]])

In [10]:
arr3d.shape

(2, 4, 3)

In [11]:
arr3d.reshape(4,6)

array([[ 1,  2,  3,  4,  5,  6],
       [10, 25, 35, 40, 50, 60],
       [10, 20, 30,  5, 10, 20],
       [11, 22, 33, 44, 55, 66]])

In [12]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
arr2d = arr.reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
arr3d = np.arange(30).reshape(2,3,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [15]:
#Bilinmeyen boyut!
#.rashape() methodu kullanılırken hesaplamak istemediğimiz boyut yerine -1 yazıp otomatik hesaplattırabiliriz.


In [16]:
arr3d = np.arange(120).reshape(5,-1,6)
arr3d

array([[[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23]],

       [[ 24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47]],

       [[ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71]],

       [[ 72,  73,  74,  75,  76,  77],
        [ 78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95]],

       [[ 96,  97,  98,  99, 100, 101],
        [102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113],
        [114, 115, 116, 117, 118, 119]]])

In [17]:
arr = np.arange(60).reshape(2,-1,5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [18]:
arr.ndim

3

In [19]:
arr.shape

(2, 6, 5)

# Arrayleri Düzleştirme(Flatten)

In [20]:
# düzleştirme işlemi(Flatten) çok boyutlu bir array'i bir boyutlu hale döndürmeye denir.
# basitce .rashape(-1) methoduyla yapılır.

In [21]:
arr2d = np.arange(40).reshape(8,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [22]:
arr2d.shape

(8, 5)

In [23]:
arr2d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [24]:
arr3d = np.arange(60).reshape(-1,5,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [25]:
arr3d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

# Çok Boyutlu Arraylerde Iteration(Yineleme)

In [26]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
for i in arr1d:
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 

In [28]:
arr2d = np.arange(20).reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
for i in arr2d:
    print(i)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [30]:
for i in arr2d:
    for j in i:
        print(j,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

# Çok boyutlu Arraylerde nditer() kullanımı

In [31]:
# For döngüsü arrayin boyutu kadar sayıda kullanılırsa ancak array'in bütün elemanlarına tek tek erişebiliriz.
# Çok boyutlu arraylerde nditer() fonksiyonu bunun için geliştirilmiştir.


In [32]:
arr3d = np.arange(30).reshape(2,3,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [33]:
for i in np.nditer(arr3d):
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 

# Array Elemanları Arasında 4 İşlem

In [34]:
arr1 = np.array([10,20,50,100])
arr2 = np.array([5,7,9,-1])

In [35]:
arr1

array([ 10,  20,  50, 100])

In [36]:
arr2

array([ 5,  7,  9, -1])

In [37]:
arr1 + arr2

array([15, 27, 59, 99])

In [38]:
arr1.__add__(arr2)

array([15, 27, 59, 99])

In [39]:
arr1 - arr2

array([  5,  13,  41, 101])

In [40]:
arr1.__sub__(arr2)

array([  5,  13,  41, 101])

In [41]:
arr1 * arr2

array([  50,  140,  450, -100])

In [42]:
arr1 / arr2

array([   2.        ,    2.85714286,    5.55555556, -100.        ])

In [43]:
arr1 // arr2

array([   2,    2,    5, -100])

# Bir Arrayin Toplamına / Ortalamasına / Varyansına / Standart Sapmasına Bakma

In [44]:
arr = np.random.randint(0,10,10)
arr

array([4, 9, 2, 0, 7, 0, 8, 9, 8, 6], dtype=int32)

In [45]:
arr.sum()

np.int64(53)

In [46]:
arr.mean() # array'in ortalamasını verir

np.float64(5.3)

In [47]:
arr.var()

np.float64(11.41)

In [48]:
arr.std()

np.float64(3.3778691508109073)

In [49]:
rst = np.random.randint(0,100,10)
rst

array([ 8,  7, 71, 94, 72,  8, 48,  2,  4, 52], dtype=int32)

In [50]:
rst.sum()

np.int64(366)

In [51]:
rst.mean()

np.float64(36.6)

In [52]:
rst.max()

np.int32(94)

In [53]:
rst.var()

np.float64(1087.04)

In [54]:
rst.std()

np.float64(32.9702896559918)

# Numpy Arraylerini Birleştirme (Concatenate)

In [55]:
#Numpy arraylerini birleştirme işlemi .concatenate() fonk. ile yapılır.Fonk. içine liste halinde birleştirilecek arrayler verilir.
#np.concatenate([arr1,arr2], axis = 0)

In [56]:
arr1 = np.array([10,20,30,30])
arr2 = np.array([100,200,600,900])


In [57]:
arr1

array([10, 20, 30, 30])

In [58]:
arr2

array([100, 200, 600, 900])

In [59]:
np.concatenate([arr1,arr2] , axis= 0) #axis = 0 yazdığımızda satır satır ekleme yapar

array([ 10,  20,  30,  30, 100, 200, 600, 900])

In [60]:
arr1  = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[100,200,300], [800,800,900]])

In [61]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
arr2

array([[100, 200, 300],
       [800, 800, 900]])

In [63]:
np.concatenate([arr1,arr2] , axis= 1)  #axis = 1 yazdığımızda stün stün ekleme yapar

array([[  1,   2,   3, 100, 200, 300],
       [  4,   5,   6, 800, 800, 900]])

# Arrayleri Stackleme(Yığınlama)İşlemleri

In [64]:
# Concatenate işleminin hemen hemen aynısıdır tek farkı yeni bir boyut(eksen) üzerinde yığınlamalar yapmasıdır.


In [65]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
arr2

array([[100, 200, 300],
       [800, 800, 900]])

In [67]:
np.concatenate([arr1,arr2] , axis= 0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [100, 200, 300],
       [800, 800, 900]])

In [68]:
np.stack([arr1,arr2] , axis = 0)

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[100, 200, 300],
        [800, 800, 900]]])

In [69]:
# np.hstack() --> Satır boyunca yığınlama
# np.vstack() --> Sütun boyunca yığınlama

# Numpy Arraylerinde İndex Arama

In [70]:
# Aradığımız değerlerin bulunduğu indexleri döndürmek için np.where() fonk. kullanırız.
#np.where() içersine argüman olarak condition(şart) alır.

In [71]:
arr =np.array([1,2,5,6,7,7,9,2,2,2])
arr

array([1, 2, 5, 6, 7, 7, 9, 2, 2, 2])

In [72]:
np.where(arr == 9)  # Arrayimizin kaçıncı indeksindeki elemanlar 9'dur ?

(array([6]),)

In [73]:
np.where(arr == 2)

(array([1, 7, 8, 9]),)

In [74]:
np.where(arr % 2 != 0)   # Tek elemanların indeksleri

(array([0, 2, 4, 5, 6]),)

# Numpy Random Kütüphanesi

In [75]:
# Random diye ayrı bir kütüphane olmasının yanı sıra NumPy kütüphanesinin içinde random adında bir modül de bulunur.
# NumPy'ın içindeki random modülü normal random kütüphanesinden daha kapsamlıdır.

In [76]:
# from numpy import random
import numpy as np

In [77]:
np.random.rand() # 0-1 arası  1 tane sayı döndürür

0.21375518482254097

In [78]:
np.random.randint(10,30,5)

array([18, 12, 15, 28, 29], dtype=int32)

In [79]:
arr

array([1, 2, 5, 6, 7, 7, 9, 2, 2, 2])

In [80]:
np.random.choice(arr)  # rastgele sayı seçer

np.int64(7)

In [81]:
np.random.choice([3,-1,15])

np.int64(3)