In [1]:
import numpy as np

In [2]:
arr0d = np.array(53)  #boyutsuz 
arr0d

array(53)

In [3]:
arr1d = np.array([1,2,3,4]) # bir boyutlu
arr1d

array([1, 2, 3, 4])

In [4]:
arr2d = np.array([[1,2,3],[4,5,6]]) # iki boyutlu
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3d = np.array([[[1,2,3], [4,5,6]] , [[7,8,9] , [100,200,300]]]) # üç boyutlu
arr3d


array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

In [6]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr3d[0,0]


array([1, 2, 3])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(30,100,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96,
       98])

In [10]:
np.linspace(30,50,6)

array([30., 34., 38., 42., 46., 50.])

In [11]:
np.linspace(30,50,6,dtype=int)

array([30, 34, 38, 42, 46, 50])

In [12]:
np.linspace(30,50,6)/10

array([3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [13]:
np.arange(10,101,5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [14]:
np.linspace(0,1000,26)

array([   0.,   40.,   80.,  120.,  160.,  200.,  240.,  280.,  320.,
        360.,  400.,  440.,  480.,  520.,  560.,  600.,  640.,  680.,
        720.,  760.,  800.,  840.,  880.,  920.,  960., 1000.])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [17]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [18]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [71]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.ones((2,3,5),dtype=int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [21]:
np.eye(5, dtype=int) # 5x5 birim matris

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## np.random

In [22]:
np.random.rand(4) #0-1 arasında rastgele sayılar verir

array([0.77631177, 0.08341302, 0.87187292, 0.1430037 ])

In [23]:
np.random.rand(2,5)

array([[0.12089671, 0.71285306, 0.59220639, 0.8120225 , 0.46071011],
       [0.3915454 , 0.47921412, 0.81535575, 0.37776202, 0.91648833]])

In [24]:
np.random.rand(4)*10  # 4 tane 0-10 aralığında sayı oluşturur

array([1.70646623, 6.61267097, 0.14446126, 6.94149497])

In [25]:
np.random.randint(15,50,5)

array([17, 33, 48, 42, 17], dtype=int32)

In [26]:
np.random.randint(0,100,(4,6))  #  0-100 sayıları arasında rastgele bir array olşturur

array([[ 7, 43, 37,  0, 78, 85],
       [45,  8, 80, 64, 34, 88],
       [90, 16, 43, 72, 48, 45],
       [36, 91, 61, 58, 94, 17]], dtype=int32)

In [27]:
np.random.randint(0,50,(4,6))

array([[31, 39, 46, 39, 28,  7],
       [25, 25, 22, 46, 38, 37],
       [36, 47, 30, 15, 35, 47],
       [ 8,  8,  5,  9, 18, 48]], dtype=int32)

# Array'lerin boyut sayısını ve Shape'ni kontrol etmek 


In [28]:
arr0d

array(53)

In [29]:
arr1d

array([1, 2, 3, 4])

In [30]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

In [32]:
#ndim   --> boyut sayısını verir
#shape  --> dizi boyutunu verir
#size   --> dizideki eleman sayısını verir
#dtype  --> dizinin eleman türünü verir,

In [33]:
arr0d.ndim

0

In [34]:
arr1d.ndim

1

In [35]:
arr2d.ndim

2

In [36]:
arr3d.ndim

3

In [37]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr2d.shape #(satir,stün)

(2, 3)

In [39]:
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

In [73]:
arr3d.size

12

In [40]:
arr3d.shape #(adet,satir,stün)

(2, 2, 3)

# Numpy Arraylerinin indeksleme ve öğelerine erişme

In [41]:
arr1d

array([1, 2, 3, 4])

In [42]:
arr1d[3]

np.int64(4)

In [43]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr2d[0]

array([1, 2, 3])

In [45]:
arr2d[1][2] # yada arr2d[3,2] yazabilirsin

np.int64(6)

In [46]:
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [100, 200, 300]]])

In [47]:
arr3d[0][1][2]  # yada arr3d[0,1,2] yazabilirsin

np.int64(6)

In [48]:
arr3d[1][0][1]

np.int64(8)

# Numpy dizilerinin Max-Min elemanlarına ve bu elemanların indexlerine erişme


In [49]:
arr = np.random.randint(1,100,10)
arr

array([42, 76, 33, 88, 43, 79, 46, 61, 78, 24], dtype=int32)

In [50]:
arr.max()

np.int32(88)

In [51]:
arr.argmax() # max sayinin index numarası

np.int64(3)

In [52]:
arr.min()

np.int32(24)

In [53]:
arr.argmin()  # min sayinin index numarası

np.int64(9)

# Numpy Arraylerinde Slicing(Dilimleme) yapılabilir

In [54]:
arr = np.arange(50,65)
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [55]:
arr[5:11]

array([55, 56, 57, 58, 59, 60])

In [56]:
arr[10:]

array([60, 61, 62, 63, 64])

In [57]:
arr[2:10:2]

array([52, 54, 56, 58])

In [58]:
arr[2:5] = 888
arr

array([ 50,  51, 888, 888, 888,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64])

In [59]:
arr1 =np.arange(-30,11)
arr1

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10])

In [60]:
arr1[5:19]

array([-25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13,
       -12])

# Bir Arrayin veri Türünü(Data Type'ını)Kontrol etme

In [61]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr.dtype

dtype('int64')

In [63]:
arr2 = np.arange(100, dtype='float')
arr2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [64]:
arr3 = np.array(['a','b','c'])
arr3

array(['a', 'b', 'c'], dtype='<U1')

In [65]:
arr3.dtype

dtype('<U1')

# Bir Arrayın dtype'ını değiştirme

In [ ]:
import numpy as np
arr = np.array([1.2, 3.5, 5.7])
arr

array([1.2, 3.5, 5.7])

In [67]:
arr.astype('int')  # (ÖNEMLİ) .astype methodu ile arraylerin dtype'ı değiştirilir.

array([1, 3, 5])

In [68]:
arr = np.array(['5' , '7' , '19' , '1' , '22' , '99' , '4'])
arr

array(['5', '7', '19', '1', '22', '99', '4'], dtype='<U2')

In [69]:
arr.astype(int)


array([ 5,  7, 19,  1, 22, 99,  4])